# Generated by Django 2.0.1 on 2018-01-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='reading date')),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
