# Generated by Django 2.0.1 on 2018-01-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='reading date'),
        ),
    ]
